"""Add embedding retry and progress states

Revision ID: 4d2c95081dd2
Revises: a542124d1db4
Create Date: 2026-07-03 11:56:14.020652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2c95081dd2'
down_revision: Union[str, None] = 'a542124d1db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('total_chunks', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('embedded_chunks', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('failed_chunks', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('current_stage', sa.String(length=64), server_default='pending', nullable=True))
    
    # Add new states to DocumentStatus ENUM manually
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE documentstatus ADD VALUE IF NOT EXISTS 'parsing'")
        op.execute("ALTER TYPE documentstatus ADD VALUE IF NOT EXISTS 'chunking'")
        op.execute("ALTER TYPE documentstatus ADD VALUE IF NOT EXISTS 'embedding'")
        op.execute("ALTER TYPE documentstatus ADD VALUE IF NOT EXISTS 'indexing'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'current_stage')
    op.drop_column('documents', 'failed_chunks')
    op.drop_column('documents', 'embedded_chunks')
    op.drop_column('documents', 'total_chunks')
    # ### end Alembic commands ###
