"""add multi-format and ocr metadata

Revision ID: a542124d1db4
Revises: 
Create Date: 2026-07-03 09:15:04.654604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a542124d1db4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_type', sa.String(length=32), server_default='pdf', nullable=False))
    op.add_column('documents', sa.Column('parser_used', sa.String(length=64), server_default='PyMuPDF', nullable=False))
    op.add_column('documents', sa.Column('ocr_used', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('documents', sa.Column('ocr_engine', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('extraction_method', sa.String(length=64), server_default='native', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extraction_method')
    op.drop_column('documents', 'ocr_engine')
    op.drop_column('documents', 'ocr_used')
    op.drop_column('documents', 'parser_used')
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###
