/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System health check
         * @description Returns the connectivity status for Gemini, PostgreSQL, and Qdrant. Overall `status` is `ok` only when all services are reachable.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload and ingest documents
         * @description Accept one or more files. Each file is:
         *     1. Validated (size limit and supported format)
         *     2. Text-extracted with the corresponding parser
         *     3. Recursively chunked
         *     4. Embedded via Gemini text-embedding-004
         *     5. Stored in Qdrant (vectors) and PostgreSQL (metadata)
         *
         *     A per-file status is returned regardless of individual failures.
         */
        post: operations["upload_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all uploaded documents
         * @description Returns a paginated list of all documents, sorted by upload date descending. Optionally filter by processing status.
         */
        get: operations["list_documents_endpoint_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a document and all its vectors
         * @description Permanently removes the document record from PostgreSQL and all associated vector embeddings from Qdrant. This operation is **irreversible**. Qdrant vectors are deleted first so the PostgreSQL record is preserved on vector-store failure, enabling safe retries.
         */
        delete: operations["delete_document_endpoint_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all Qdrant collections
         * @description Returns all collections present in the Qdrant instance, each with a lightweight stats snapshot (vector count, points count, status).
         */
        get: operations["list_collections_endpoint_collections_get"];
        put?: never;
        /**
         * Create a new Qdrant collection
         * @description Creates a new vector collection with the specified configuration. A `document_id` keyword payload index is created automatically. Returns the full collection details as stored in Qdrant.
         */
        post: operations["create_collection_endpoint_collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get collection details
         * @description Returns full configuration and runtime statistics for the named collection (vector count, index status, segment count, vector config).
         */
        get: operations["get_collection_endpoint_collections__name__get"];
        put?: never;
        post?: never;
        /**
         * Delete a Qdrant collection
         * @description Permanently deletes the named collection and **all** its vectors. This operation is **irreversible**.
         *
         *     > **Note**: The primary RAG collection (configured via `QDRANT_COLLECTION`) is protected and cannot be deleted through this endpoint. Use `DELETE /documents/{id}` to remove individual documents.
         */
        delete: operations["delete_collection_endpoint_collections__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * RAG query with streaming response
         * @description Submit a natural-language question. The response is a **Server-Sent Events** stream.
         *
         *     Set `Accept: text/event-stream` or simply consume the stream — FastAPI will set `Content-Type: text/event-stream` automatically.
         *
         *     **Event types** (in order):
         *     - `thinking` — pipeline started
         *     - `sources`  — retrieved document chunks (before any tokens)
         *     - `chunk`    — one LLM token or small token batch
         *     - `done`     — answer complete; includes `conversation_id` for follow-up
         *     - `error`    — unrecoverable failure (stream still closes cleanly)
         *
         *     Pass the returned `conversation_id` in subsequent requests to continue the conversation with full memory.
         */
        post: operations["query_endpoint_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_documents_upload_post */
        Body_upload_documents_upload_post: {
            /**
             * Files
             * @description One or more files (max 50 MB each).
             */
            files: string[];
        };
        /**
         * CollectionCreate
         * @description Payload to create a new Qdrant collection.
         * @example {
         *       "distance": "Cosine",
         *       "name": "my_collection",
         *       "on_disk_payload": true,
         *       "vector_size": 768
         *     }
         */
        CollectionCreate: {
            /**
             * Name
             * @description Collection name (alphanumeric, underscores, hyphens only).
             */
            name: string;
            /**
             * Vector Size
             * @description Dimensionality of vectors (default: 768 for text-embedding-004).
             * @default 768
             */
            vector_size: number;
            /**
             * @description Distance metric used for similarity search.
             * @default Cosine
             */
            distance: components["schemas"]["DistanceMetric"];
            /**
             * On Disk Payload
             * @description Store payload on disk to reduce RAM usage.
             * @default true
             */
            on_disk_payload: boolean;
        };
        /**
         * CollectionDeleteResponse
         * @description Confirmation returned after a successful collection deletion.
         * @example {
         *       "message": "Collection deleted successfully.",
         *       "name": "my_collection"
         *     }
         */
        CollectionDeleteResponse: {
            /** Name */
            name: string;
            /**
             * Message
             * @default Collection deleted successfully.
             */
            message: string;
        };
        /**
         * CollectionInfo
         * @description Full details for a single Qdrant collection.
         * @example {
         *       "indexed_vectors_count": 15000,
         *       "name": "documents",
         *       "points_count": 15000,
         *       "segments_count": 2,
         *       "status": "green",
         *       "vector_count": 15000,
         *       "vectors_config": {
         *         "distance": "Cosine",
         *         "size": 768
         *       }
         *     }
         */
        CollectionInfo: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Vector Count
             * @default 0
             */
            vector_count: number;
            /**
             * Indexed Vectors Count
             * @default 0
             */
            indexed_vectors_count: number;
            /**
             * Points Count
             * @default 0
             */
            points_count: number;
            /**
             * Segments Count
             * @default 0
             */
            segments_count: number;
            vectors_config?: components["schemas"]["VectorsConfig"] | null;
        };
        /**
         * CollectionListResponse
         * @description Paginated list of all Qdrant collections.
         */
        CollectionListResponse: {
            /** Total */
            total: number;
            /** Collections */
            collections: components["schemas"]["CollectionSummary"][];
        };
        /**
         * CollectionSummary
         * @description Lightweight entry used in list responses.
         */
        CollectionSummary: {
            /** Name */
            name: string;
            /**
             * Vector Count
             * @default 0
             */
            vector_count: number;
            /**
             * Points Count
             * @default 0
             */
            points_count: number;
            /**
             * Status
             * @default unknown
             */
            status: string;
        };
        /**
         * DistanceMetric
         * @enum {string}
         */
        DistanceMetric: "Cosine" | "Dot" | "Euclid" | "Manhattan";
        /**
         * DocumentDeleteResponse
         * @description Confirmation returned after a successful document deletion.
         * @example {
         *       "document_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "filename": "annual_report.pdf",
         *       "message": "Document and associated vectors deleted successfully."
         *     }
         */
        DocumentDeleteResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Filename */
            filename: string;
            /**
             * Message
             * @default Document and associated vectors deleted successfully.
             */
            message: string;
        };
        /**
         * DocumentListResponse
         * @description Paginated list of documents.
         * @example {
         *       "documents": [],
         *       "limit": 20,
         *       "page": 1,
         *       "pages": 3,
         *       "total": 42
         *     }
         */
        DocumentListResponse: {
            /**
             * Total
             * @description Total documents matching the filter
             */
            total: number;
            /**
             * Page
             * @description Current page (1-indexed)
             */
            page: number;
            /**
             * Limit
             * @description Items per page
             */
            limit: number;
            /**
             * Pages
             * @description Total number of pages
             */
            pages: number;
            /** Documents */
            documents: components["schemas"]["DocumentSummary"][];
        };
        /**
         * DocumentResult
         * @description Result for a single uploaded file.
         * @example {
         *       "chunk_count": 178,
         *       "created_at": "2026-07-02T11:00:00Z",
         *       "document_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "file_size_bytes": 4194304,
         *       "filename": "annual_report.pdf",
         *       "page_count": 42,
         *       "status": "completed"
         *     }
         */
        DocumentResult: {
            /** Document Id */
            document_id?: string | null;
            /** Filename */
            filename: string;
            status: components["schemas"]["DocumentStatus"];
            /** Page Count */
            page_count?: number | null;
            /** Chunk Count */
            chunk_count?: number | null;
            /** File Size Bytes */
            file_size_bytes?: number | null;
            /** Error */
            error?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Message */
            message?: string | null;
            /** Existing Document Id */
            existing_document_id?: string | null;
            /** Uploaded At */
            uploaded_at?: string | null;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "pending" | "parsing" | "chunking" | "embedding" | "indexing" | "completed" | "failed" | "already_exists";
        /**
         * DocumentSummary
         * @description Lightweight document row — used in paginated list responses.
         */
        DocumentSummary: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Filename */
            filename: string;
            status: components["schemas"]["DocumentStatus"];
            /** Page Count */
            page_count: number;
            /** Chunk Count */
            chunk_count: number;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @example {
         *       "gemini": "connected",
         *       "postgres": "connected",
         *       "qdrant": "connected",
         *       "status": "ok"
         *     }
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Gemini
             * @enum {string}
             */
            gemini: "connected" | "not_connected";
            /**
             * Postgres
             * @enum {string}
             */
            postgres: "connected" | "not_connected";
            /**
             * Qdrant
             * @enum {string}
             */
            qdrant: "connected" | "not_connected";
        };
        /**
         * QueryRequest
         * @description Body accepted by POST /query.
         * @example {
         *       "query": "What are the main risk factors discussed in the report?",
         *       "top_k": 5
         *     }
         */
        QueryRequest: {
            /**
             * Query
             * @description The user's natural-language question.
             */
            query: string;
            /**
             * Conversation Id
             * @description UUID of an existing conversation to continue. Omit (or send null) to start a new conversation.
             */
            conversation_id?: string | null;
            /**
             * Top K
             * @description Number of document chunks to retrieve from the vector store.
             * @default 5
             */
            top_k: number;
        };
        /**
         * UploadResponse
         * @description Aggregated result returned by POST /upload.
         * @example {
         *       "documents": [],
         *       "failed": 0,
         *       "succeeded": 2,
         *       "total": 2
         *     }
         */
        UploadResponse: {
            /**
             * Total
             * @description Total files submitted
             */
            total: number;
            /**
             * Succeeded
             * @description Files processed successfully
             */
            succeeded: number;
            /**
             * Failed
             * @description Files that encountered errors
             */
            failed: number;
            /** Documents */
            documents: components["schemas"]["DocumentResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VectorsConfig
         * @description Vector configuration details for a collection.
         */
        VectorsConfig: {
            /** Size */
            size: number;
            /** Distance */
            distance: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    upload_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_endpoint_documents_get: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed). */
                page?: number;
                /** @description Items per page (max 100). */
                limit?: number;
                /** @description Filter by document status. */
                status?: components["schemas"]["DocumentStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_endpoint_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the document to delete. */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collections_endpoint_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListResponse"];
                };
            };
        };
    };
    create_collection_endpoint_collections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_endpoint_collections__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection name. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_collection_endpoint_collections__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection name to delete. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_endpoint_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description SSE stream of RAG events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation error — invalid request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
